name: ML Workflow CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.7'

      - name: Install Dependencies
        run: |
          pip install mlflow==2.19.0 pandas scikit-learn numpy

      - name: Run MLflow Project
        run: |
          cd MLProject_folder
          # Menggunakan env-manager=local agar CI berjalan lebih cepat
          mlflow run . --env-manager=local

      - name: Simpan Artefak ke GitHub
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-artifacts
          path: MLProject_folder/mlruns/

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Generate Dockerfile & Patch Bug Pip 3.9
        env:
          MLFLOW_TRACKING_URI: "file://${{ github.workspace }}/MLProject_folder/mlruns"
        run: |
          cd MLProject_folder
          RUN_ID=$(cat run_id.txt)
          
          # 1. Minta MLflow membuat cetak biru (Dockerfile) saja
          mlflow models generate-dockerfile -m "runs:/$RUN_ID/model" -d docker_build_dir
          
          # 2. Ganti tautan get-pip yang rusak ke versi khusus 3.9 secara otomatis
          sed -i 's|https://bootstrap.pypa.io/get-pip.py|https://bootstrap.pypa.io/pip/3.9/get-pip.py|g' docker_build_dir/Dockerfile
          
          # 3. Rakit Docker Image secara manual menggunakan cetak biru yang sudah diperbaiki
          cd docker_build_dir
          docker build -t ${{ secrets.DOCKER_USERNAME }}/credit-risk-model:latest .

      - name: Push Image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/credit-risk-model:latest